[project]
name = "hospitopt-api"
version = "0.2.0"
description = "FastAPI REST API for hospitopt"
readme = "README.md"
authors = [
    { name = "Daniel Sousa", email = "danielsoussa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "hospitopt-core",
    "fastapi>=0.128.0",
    "uvicorn>=0.40.0",
]

[tool.uv.sources]
hospitopt-core = { workspace = true }

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
