{{- if .Values.api.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hospitopt.fullname" . }}-api
  labels:
    {{- include "hospitopt.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: api
      {{- include "hospitopt.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: api
        {{- include "hospitopt.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: api
          image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag }}
          imagePullPolicy: {{ .Values.api.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: API_CONFIG_FILE_PATH
              value: /app/configs/api.yaml
            - name: HOSPITOPT_DB_HOST
              value: {{ .Values.postgresql.fullnameOverride | quote }}
            - name: HOSPITOPT_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.postgresql.fullnameOverride | quote }}
                  key: password
            - name: HOSPITOPT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hospitopt.fullname" . }}-secrets
                  key: HOSPITOPT_API_KEY
          volumeMounts:
            - name: config
              mountPath: /app/configs
              readOnly: true
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            {{- toYaml .Values.api.resources | nindent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "hospitopt.fullname" . }}-config
            items:
              - key: api.yaml
                path: api.yaml
{{- end }}
