apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hospitopt.fullname" . }}-config
  labels:
    {{- include "hospitopt.labels" . | nindent 4 }}
data:
  api.yaml: |
{{ .Values.config.apiYaml | indent 4 }}
  worker.yaml: |
{{ .Values.config.workerYaml | indent 4 }}
