[project]
name = "hospitopt-core"
version = "0.1.0"
description = "Core domain models, database, and configuration for hospitopt"
readme = "README.md"
authors = [
    { name = "Daniel Sousa", email = "danielsoussa@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.1",
    "asyncpg>=0.31.0",
    "loguru>=0.7.3",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.12.0",
    "python-dotenv>=1.2.1",
    "pyyaml>=6.0.3",
    "sqlalchemy>=2.0.46",
]

[build-system]
requires = ["uv_build>=0.9.24,<0.10.0"]
build-backend = "uv_build"
