# yaml-language-server: $schema=../schemas/api-schema.json

api_key: ENV("HOSPITOPT_API_KEY")

db_connection:
  host: ENV("HOSPITOPT_DB_HOST")
  port: 5432
  database: hospitopt
  user: hospitopt_user
  password: ENV("HOSPITOPT_DB_PASSWORD")

cors:
  allow_origins:
    - http://localhost:3000
    - http://127.0.0.1:3000
    - http://localhost:8001
    - http://127.0.0.1:8001
  allow_credentials: true
  allow_methods:
    - GET
    - OPTIONS
  allow_headers:
    - "*"
