# yaml-language-server: $schema=../schemas/config.json
ingestion:
  type: db
  host: localhost
  port: 5432
  database: hospitopt
  user: hospitopt_user
  password: ENV("HOSPITOPT_DB_PASSWORD")

worker:
  poll_interval_seconds: 10.0
  google_maps_api_key: ENV("GOOGLE_MAPS_API_KEY")
  db_connection:
    host: localhost
    port: 5432
    database: hospitopt
    user: hospitopt_user
    password: ENV("HOSPITOPT_DB_PASSWORD")

api:
  api_key: ENV("HOSPITOPT_API_KEY")
  cors:
    allow_origins:
      - http://localhost:3000
      - http://127.0.0.1:3000
      - http://localhost:8001
      - http://127.0.0.1:8001
    allow_credentials: true
    allow_methods:
      - GET
      - OPTIONS
    allow_headers:
      - "*"
