ingestion:
  type: db
  host: localhost
  port: 5432
  database: hospitopt
  user: hospitopt_user
  password: ENV("HOSPITOPT_DB_PASSWORD")

worker:
  poll_interval_seconds: 10.0
  google_maps_api_key: ENV("GOOGLE_MAPS_API_KEY")
  db_connection:
    host: localhost
    port: 5432
    database: hospitopt
    user: hospitopt_user
    password: ENV("HOSPITOPT_DB_PASSWORD")
