# yaml-language-server: $schema=../schemas/worker-schema.json

poll_interval_seconds: 10.0
google_maps_api_key: ENV("GOOGLE_MAPS_API_KEY")
db_connection:
  host: ENV("HOSPITOPT_DB_HOST")
  port: 5432
  database: hospitopt
  user: hospitopt_user
  password: ENV("HOSPITOPT_DB_PASSWORD")

ingestion:
  type: db
  host: ENV("HOSPITOPT_DB_HOST")
  port: 5432
  database: hospitopt
  user: hospitopt_user
  password: ENV("HOSPITOPT_DB_PASSWORD")
